FROM aditrohr/base-image:latest

# Import certificate and grant IIS access to it
COPY ["./cert","/cert"]
RUN certutil -f -p password -importPFX c:\cert\competence-web.pfx; \
	takeown /f 'C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\*'; \
	icacls 'C:\ProgramData\Microsoft\Crypto\RSA\MachineKeys\*' /grant everyone:RX

# Add local integration folders which is mapped to integration folder using a drive on the host
RUN New-Item -Path 'C:\Data\Export\Competence' -ItemType Directory;
RUN New-Item -Path 'C:\Data\Import\Competence\ImportMe' -ItemType Directory;
RUN New-Item -Path 'C:\Data\Import\Competence\Imported' -ItemType Directory;
RUN New-Item -Path 'C:\Data\Import\Competence\Failed' -ItemType Directory;

RUN New-WebAppPool -Name 'Competence AppPool'; \
	$AppPool = Get-Item 'IIS:\AppPools\Competence AppPool'; \
	$AppPool.enable32BitAppOnWin64 = $True; \
	$AppPool.startMode = 'AlwaysRunning'; \
	$AppPool.processModel.loadUserProfile = $True; \
	$AppPool.processModel.idleTimeout = [TimeSpan]::FromMinutes(0); \
	$AppPool.recycling.periodicRestart.time = '00:00:00'; \
	$AppPool | Set-Item; \
	Set-ItemProperty 'IIS:\AppPools\Competence AppPool' -Name recycling.periodicRestart.schedule -Value @{value='05:10:00'}; \
	New-Item -Path 'C:\Aditro\wwwroot\Competence' -ItemType Directory; \
	New-WebApplication -Site 'Default Web Site' -Name '__APPLICATION_NAM' -PhysicalPath 'C:\Aditro\wwwroot\Competence' -ApplicationPool 'Competence AppPool'; \
	Set-ItemProperty -Path 'IIS:\Sites\Default Web Site\__APPLICATION_NAME' -Name preloadEnabled -Value $True

	
RUN New-WebAppPool -Name 'CompetenceServices AppPool'; \
	$AppPool = Get-Item 'IIS:\AppPools\CompetenceServices AppPool'; \
	$AppPool.enable32BitAppOnWin64 = $True; \
	$AppPool.startMode = 'AlwaysRunning'; \
	$AppPool.processModel.loadUserProfile = $True; \
	$AppPool.processModel.idleTimeout = [TimeSpan]::FromMinutes(0); \
	$AppPool.recycling.periodicRestart.time = '00:00:00'; \
	$AppPool | Set-Item; \
	Set-ItemProperty 'IIS:\AppPools\Competence AppPool' -Name recycling.periodicRestart.schedule -Value @{value='05:10:00'}; \
	New-Item -Path 'C:\Aditro\wwwroot\Services' -ItemType Directory; \
	New-WebVirtualDirectory -Site 'Default Web Site' -Name 'Services' -PhysicalPath 'C:\Aditro\wwwroot\Services'; \
	New-Item -Path 'C:\Aditro\wwwroot\Services\CompetenceServices' -ItemType Directory; \
	New-WebApplication -Site 'Default Web Site' -Name 'Services/CompetenceServices' -PhysicalPath 'C:\Aditro\wwwroot\Services\CompetenceServices' -ApplicationPool 'CompetenceServices AppPool'; \
	Set-ItemProperty -Path 'IIS:\Sites\Default Web Site\Services\CompetenceServices' -Name preloadEnabled -Value $True

RUN Import-Module WebAdministration; \
	Set-ItemProperty -Path 'IIS:\Sites\Default Web Site\Services\CompetenceServices' -Name enabledProtocols -Value 'http,net.tcp'

COPY ["./Competence","/Aditro/wwwroot/Competence"]
COPY ["./Services/CompetenceServices","/Aditro/wwwroot/Services/CompetenceServices"]

